### ISSUE TITLE
Original concept

### ISSUE THREAD

**Issue by simonjhogan** [sleuth255/playz-emby#2]
Mate, common courtesy would be to give the original author credit for the code you have forked from.

Ideally you should be feeding your changes back into the original code base, which is why I shared the code in the first place.

Cheers,

Simon J. Hogan

**Comment by sleuth255** [comment]
Happy to do that.  I preserved all of your author comments in the code which I thought was sufficient.  I can add credits to the splash screen too.  How would you like the credits posted? Name or Company or both?

What else would you like?  I certainly don’t intend to profit from this; the app will be published as a freebie.

I started a new repo because I have intentions to completely revamp the catalog logic (home.js, collection.js, item.js, renderer.js) which is really the heart of this code.  Also, I’m actually just using playz-emby as a learning tool to help me get up to speed on emby client dev.  As such, I felt that it would be important to leave your original repo alone since I do see this one diverging significantly as I learn more.
